# Generated by Django 3.0.6 on 2020-10-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaDataPDB',
        ),
    ]
