# Generated by Django 3.0.6 on 2020-10-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limb', '0005_auto_20201015_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalsite',
            name='representative',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
