# Generated by Django 3.0.6 on 2020-12-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limb', '0007_auto_20201026_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBcomposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNA_protein_RNA', models.IntegerField()),
                ('DNA_protein', models.IntegerField()),
                ('DNA_RNA', models.IntegerField()),
                ('protein_RNA', models.IntegerField()),
                ('protein_protein', models.IntegerField()),
                ('DNA_DNA', models.IntegerField()),
                ('RNA_RNA', models.IntegerField()),
                ('other_complexes', models.IntegerField()),
                ('representative', models.BooleanField(blank=True, null=True)),
                ('element', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'DBcomposition',
            },
        ),
    ]
